services:
  app:
    container_name: emd-devops-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    environment:
      - ENV=development
      - DEBUG=True

    volumes:
      - .:/app
